site_name: Trencadís RTL
docs_dir: doc
theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.top

nav:
  - 'Home': 'index.md'
  - 'Contributing': 'CONTRIBUTING.md'
  - 'Datasheets':
    - 'Register File': './datasheets/components/register_file.md'