site_name: Trencadís RTL
docs_dir: doc
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Home': 'index.md'
  - 'Contributing': 'CONTRIBUTING.md'
  - 'Datasheets':
    - 'Register File': 'datasheets_md/components/trencadis_register_file.md'
    - 'Pulse Generator': 'datasheets_md/components/trencadis_pulse_generator.md'