name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check_ci_status:
    name: ✅ Verify Successful CI Run
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Check status of CI workflow for this commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conclusion=$(gh run list --workflow "ci.yml" --commit ${{ github.sha }} --branch main --json conclusion --jq '.[0].conclusion')
          if [[ -z "$conclusion" ]]; then
            echo "Error: No matching CI workflow run found for commit ${{ github.sha }} on branch main."
            exit 1
          fi
          echo "CI workflow conclusion for this commit is: $conclusion"
          if [[ "$conclusion" != "success" ]]; then
            echo "CI workflow did not succeed. Halting release."
            exit 1
          fi
          echo "CI check passed!"

  build_assets:
    name: 📦 Package Release Assets
    runs-on: ubuntu-latest
    needs: check_ci_status
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python & System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango-1.0-0 libpangoft2-1.0-0
          pip install markdown2 weasyprint
      - name: Generate PDF Datasheets
        run: python doc/generate_datasheets.py
      - name: Package Release Archive
        run: |
          VERSION=${GITHUB_REF##*/}
          zip -r Trencadis-RTL-Release-${VERSION}.zip rtl/ verification/tb/ doc/datasheets_pdf/ examples/
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: Trencadis-RTL-Release-*.zip

  create_release:
    name: 🚀 Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_assets
    permissions:
      contents: write
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Trencadis-RTL-Release-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          append_body: true
          body: |
            ---
            **📖 View the full documentation for this version online:**
            [https://Bubi2001.github.io/Trencadis-RTL/](https://Bubi2001.github.io/Trencadis-RTL/)
