name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test_before_release:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Run Linter & Verification
        run: |
          echo "Linting all files..."
          chmod +x ./verification/scripts/run_lint.sh
          ./verification/scripts/run_lint.sh
          echo "Running all tests..."
          chmod +x ./verification/scripts/run_all_tests.sh
          ./verification/scripts/run_all_tests.sh

  build_assets:
    name: 📦 Package Release Assets
    runs-on: ubuntu-latest
    needs: test_before_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python & System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango-1.0-0 libpangoft2-1.0-0
          pip install markdown2 weasyprint
      - name: Generate PDF Datasheets
        run: python doc/generate_datasheets.py
      - name: Package Release Archive
        run: |
          VERSION=${GITHUB_REF##*/}
          zip -r Trencadis-RTL-Release-${VERSION}.zip rtl/ verification/tb/ doc/datasheets_pdf/ examples/
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: Trencadis-RTL-Release-*.zip

  create_release:
    name: 🚀 Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_assets
    permissions:
      contents: write
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Trencadis-RTL-Release-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          append_body: true
          body: |
            ---
            **📖 View the full documentation for this version online:**
            [https://Bubi2001.github.io/Trencadis-RTL/](https://Bubi2001.github.io/Trencadis-RTL/)
