name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test_before_release:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Verilator
        run: sudo apt-get update && sudo apt-get install -y verilator
      - name: Run Linter & Verification
        run: |
          echo "Linting all files..."
          find rtl/ -name "*.sv" -print0 | while IFS= read -r -d $'\0' file; do verilator --lint-only -sv -Irtl/peripherals -Irtl/components -Irtl/arithmetic "$file" || exit 1; done
          echo "Running all tests..."
          chmod +x ./verification/scripts/run_all_tests.sh
          ./verification/scripts/run_all_tests.sh

  build_assets:
    name: 📦 Build Release Assets
    runs-on: ubuntu-latest
    needs: test_before_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Build PDF from documentation
        run: |
          pandoc doc/*.md -o Trencadis-RTL-Docs.pdf --pdf-engine=xelatex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: Trencadis-RTL-Docs.pdf

  create_release:
    name: 🚀 Create GitHub Release
    runs-on: ubuntu-latest
    needs: build_assets
    permissions:
      contents: write
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Trencadis-RTL-Docs.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true